theme: jekyll-theme-minimal
title: Giacomo Veneri's homepage
description: Bookmark this to keep an eye on my project updates! [BLOG](https://jugsi.blogspot.coms)

baseurl: "" # the subpath of your site, e.g. /blog

twitter_username: venergiac
github_username:  venergiac
